<?php

namespace rpf\apiResponse\module;
use rpf\apiResponse\apiResponseModule;

/**
 * Class bbDomain_readEntry
 *
 * !! DO NOT EDIT THIS FILE !!
 * (It's generated automatically)
 */
class bbDomain_readEntry extends apiResponseModule
{
    /**
     * @return integer $this->rpcResponse[seid]
     */
    public function getSeid()
    {
        return $this->rpcResponse['seid'];
    }

    /**
     * @return string $this->rpcResponse[p_seid]
     */
    public function getPSeid()
    {
        return $this->rpcResponse['p_seid'];
    }

    /**
     * @return string $this->rpcResponse[oeid]
     */
    public function getOeid()
    {
        return $this->rpcResponse['oeid'];
    }

    /**
     * @return integer $this->rpcResponse[pk]
     */
    public function getPk()
    {
        return $this->rpcResponse['pk'];
    }

    /**
     * @return string $this->rpcResponse[typ]
     */
    public function getTyp()
    {
        return $this->rpcResponse['typ'];
    }

    /**
     * @return string $this->rpcResponse[p_typ]
     */
    public function getPTyp()
    {
        return $this->rpcResponse['p_typ'];
    }

    /**
     * @return string $this->rpcResponse[data_md5]
     */
    public function getDataMd5()
    {
        return $this->rpcResponse['data_md5'];
    }

    /**
     * @return integer $this->rpcResponse[gen_uid]
     */
    public function getGenUid()
    {
        return $this->rpcResponse['gen_uid'];
    }

    /**
     * @return integer $this->rpcResponse[gen_date]
     */
    public function getGenDate()
    {
        return $this->rpcResponse['gen_date'];
    }

    /**
     * @return integer $this->rpcResponse[upd_uid]
     */
    public function getUpdUid()
    {
        return $this->rpcResponse['upd_uid'];
    }

    /**
     * @return integer $this->rpcResponse[upd_date]
     */
    public function getUpdDate()
    {
        return $this->rpcResponse['upd_date'];
    }

    /**
     * @return integer $this->rpcResponse[cache_date]
     */
    public function getCacheDate()
    {
        return $this->rpcResponse['cache_date'];
    }

    /**
     * @return integer $this->rpcResponse[expire_date]
     */
    public function getExpireDate()
    {
        return $this->rpcResponse['expire_date'];
    }

    /**
     * @return integer $this->rpcResponse[load_date]
     */
    public function getLoadDate()
    {
        return $this->rpcResponse['load_date'];
    }

    /**
     * @return string $this->rpcResponse[managed]
     */
    public function getManaged()
    {
        return $this->rpcResponse['managed'];
    }

    /**
     * @return string $this->rpcResponse[so_status]
     */
    public function getSoStatus()
    {
        return $this->rpcResponse['so_status'];
    }

    /**
     * @return string $this->rpcResponse[ordnr]
     */
    public function getOrdnr()
    {
        return $this->rpcResponse['ordnr'];
    }

    /**
     * @return string $this->rpcResponse[accounted_till]
     */
    public function getAccountedTill()
    {
        return $this->rpcResponse['accounted_till'];
    }

    /**
     * @return integer $this->rpcResponse[dn]
     */
    public function getDn()
    {
        return $this->rpcResponse['dn'];
    }

    /**
     * @return integer $this->rpcResponse[name]
     */
    public function getName()
    {
        return $this->rpcResponse['name'];
    }

    /**
     * @return integer $this->rpcResponse[bestellt]
     */
    public function getBestellt()
    {
        return $this->rpcResponse['bestellt'];
    }

    /**
     * @return string $this->rpcResponse[freigeschaltet]
     */
    public function getFreigeschaltet()
    {
        return $this->rpcResponse['freigeschaltet'];
    }

    /**
     * @return integer $this->rpcResponse[ablaufdatum]
     */
    public function getAblaufdatum()
    {
        return $this->rpcResponse['ablaufdatum'];
    }

    /**
     * @return string $this->rpcResponse[ablaufstatus]
     */
    public function getAblaufstatus()
    {
        return $this->rpcResponse['ablaufstatus'];
    }

    /**
     * @return integer $this->rpcResponse[domainprovider]
     */
    public function getDomainprovider()
    {
        return $this->rpcResponse['domainprovider'];
    }

    /**
     * @return integer $this->rpcResponse[can_cgi]
     */
    public function getCanCgi()
    {
        return $this->rpcResponse['can_cgi'];
    }

    /**
     * @return string $this->rpcResponse[authcode]
     */
    public function getAuthcode()
    {
        return $this->rpcResponse['authcode'];
    }

    /**
     * @return string $this->rpcResponse[is_kk]
     */
    public function getIsKk()
    {
        return $this->rpcResponse['is_kk'];
    }

    /**
     * @return string $this->rpcResponse[nserver1]
     */
    public function getNserver1()
    {
        return $this->rpcResponse['nserver1'];
    }

    /**
     * @return string $this->rpcResponse[nserver2]
     */
    public function getNserver2()
    {
        return $this->rpcResponse['nserver2'];
    }

    /**
     * @return string $this->rpcResponse[nserver3]
     */
    public function getNserver3()
    {
        return $this->rpcResponse['nserver3'];
    }

    /**
     * @return string $this->rpcResponse[nserver4]
     */
    public function getNserver4()
    {
        return $this->rpcResponse['nserver4'];
    }

    /**
     * @return string $this->rpcResponse[nserver1_ip]
     */
    public function getNserver1Ip()
    {
        return $this->rpcResponse['nserver1_ip'];
    }

    /**
     * @return string $this->rpcResponse[nserver2_ip]
     */
    public function getNserver2Ip()
    {
        return $this->rpcResponse['nserver2_ip'];
    }

    /**
     * @return string $this->rpcResponse[nserver3_ip]
     */
    public function getNserver3Ip()
    {
        return $this->rpcResponse['nserver3_ip'];
    }

    /**
     * @return string $this->rpcResponse[nserver4_ip]
     */
    public function getNserver4Ip()
    {
        return $this->rpcResponse['nserver4_ip'];
    }

    /**
     * @return string $this->rpcResponse[type]
     */
    public function getType()
    {
        return $this->rpcResponse['type'];
    }

    /**
     * @return string $this->rpcResponse[bounce]
     */
    public function getBounce()
    {
        return $this->rpcResponse['bounce'];
    }

    /**
     * @return string $this->rpcResponse[status]
     */
    public function getStatus()
    {
        return $this->rpcResponse['status'];
    }

    /**
     * @return integer $this->rpcResponse[is_free]
     */
    public function getIsFree()
    {
        return $this->rpcResponse['is_free'];
    }

    /**
     * @return array $this->rpcResponse[handles]
     */
    public function getHandles()
    {
        return $this->rpcResponse['handles'];
    }

    /**
     * @return array $this->rpcResponse[nameserver]
     */
    public function getNameserver()
    {
        return $this->rpcResponse['nameserver'];
    }

    /**
     * @return array $this->rpcResponse[major]
     */
    public function getMajor()
    {
        return $this->rpcResponse['major'];
    }

}
