<?php
/**
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !! DO NOT EDIT THIS FILE !!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!
 *
 * If you need to edit some configurations, please copy this file and rename it as config.php
 */

// RPC-URL (gets auto dectected from path if DF-Auftragsnummer is not defined below)
// If you're in trouble with login, please enter your DF-Auftragsnummer below (without A-Prefix)
// See: https://github.com/ADoebeling/RP2-Framework/issues/15
defined('RPF_API_MODULE_BBRPC_AUTH_DF_ORDER') or        define('RPF_API_MODULE_BBRPC_AUTH_DF_ORDER', false);
defined('RPF_API_MODULE_BBRPC_SETURL_PATTERN') or       define('RPF_API_MODULE_BBRPC_SETURL_PATTERN', 'https://%u.premium-admin.eu/');
defined('RPF_API_MODULE_BBRPC_SETURL_URL') or           define('RPF_API_MODULE_BBRPC_SETURL_URL', sprintf(RPF_API_MODULE_BBRPC_SETURL_PATTERN, RPF_API_MODULE_BBRPC_AUTH_DF_ORDER));

// RPC-User (gets requested by http-auth if not set)
defined('RPF_API_MODULE_BBRPC_AUTH_USER') or            define('RPF_API_MODULE_BBRPC_AUTH_USER', false);
defined('RPF_API_MODULE_BBRPC_AUTH_PASSWORD') or        define('RPF_API_MODULE_BBRPC_AUTH_PASSWORD', false);

// The RPC-COOKIE
defined('RPF_API_MODULE_AUTH_COOKIE') or                define('RPF_API_MODULE_AUTH_COOKIE', '/tmp/rpf.rpc.cookie');

// Debug-Mode? (Logging)
defined('RPF_DEBUG') or                                 define('RPF_DEBUG', true);

defined('RPF_SYSTEM_MODULE_LOG_DIR') or                 define('RPF_SYSTEM_MODULE_LOG_DIR', __DIR__.'/../logs/');


// Some PHP-settings
error_reporting(E_ALL);
setlocale (LC_ALL, 'de_DE@euro', 'de_DE', 'de', 'ge');
mb_internal_encoding("UTF-8");
spl_autoload_register('\rpf\classLoader');
set_exception_handler('\rpf\exceptionHandler');
set_error_handler('\rpf\errorHandler');